version: 2
jobs:
  build:
    docker:
      - image: golang:1.10
    working_directory: /go/src/zondax/ledger-cosmos-go
    steps:
      - checkout
      - run: go get -v -u github.com/golang/dep/cmd/dep
      - run: dep ensure -v
      - run: go build
      - run: go test
workflows:
  version: 2
  build_all:
    jobs:
      - build
